### ISSUE TITLE
merkwürdig, merkwürdig, wo isset hin? 

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#20]
Bei abgabe der Wohnung wurde diese nicht gefunden

org.immopoly.appengine.ImmopolyServlet doGet: ImmopolyException /portfolio/remove
org.immopoly.common.ImmopolyException: merkwürdig, merkwürdig, wo isset hin? 
    at org.immopoly.appengine.actions.ActionExposeRemove.execute(ActionExposeRemove.java:90)
    at org.immopoly.appengine.ImmopolyServlet.doGet(ImmopolyServlet.java:87)

**Comment by mrschtief** [comment]
3 Bugs in einem, zuerst neuer Fehlercode von IS24 dann wurde ein Error zurückgegeben und die Wohnung nicht removed. 
Und in Android wird die Wohnung trotz errors auch nicht removed, bleibt also ewig drin.

Ich gebe jetzt erstmal kein Fehler mehr zurück geben sondern schreibe in die Historie das die Wohnung nicht gefunden wurde und es keine Strafe gibt

**Comment by mrschtief** [comment]
hab jetzt wieder die Exception geschmissen und hoffe das Problem tritt nicht mehr auf.
